language: java

# TO get more memory: https://docs.travis-ci.com/user/reference/overview/
sudo: required

jdk:
  - openjdk8

addons:
  chrome: stable

install: # Install ChromeDriver
  - wget -N https://chromedriver.storage.googleapis.com/77.0.3865.40/chromedriver_linux64.zip -P ~/
  - unzip ~/chromedriver_linux64.zip -d ~/
  - rm ~/chromedriver_linux64.zip
  - sudo mv -f ~/chromedriver /usr/local/share/
  - sudo chmod +x /usr/local/share/chromedriver
  - sudo ln -s /usr/local/share/chromedriver /usr/local/bin/chromedriver

env:
  - MAVEN_OPTS=-Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn

script: xvfb-run --server-args="-screen 0 1920x1080x24" mvn -B clean verify failsafe:verify

cache:
  directories:
    - $HOME/.m2
