language: java

# To get more memory: https://docs.travis-ci.com/user/reference/overview/
sudo: false

cache:
  directories:
    - $HOME/.m2

jdk:
  - openjdk8

addons:
  chrome: stable
  apt:
    packages:
      - chromium-chromedriver

services:
  - xvfb

env:
  - MAVEN_OPTS=-Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn

script:
  - mvn -B clean verify failsafe:verify
